name: cicd


on:
  workflow_dispatch:

env:
  AZURE_CONTAINER_REPOSITORY: 'lbcluster'
  AZURE_CONTAINER_REGISTRY: 'lbkubernetestestacr.azurecr.io'


dockerBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Docker login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./
          push: true
          tags: ${{ secrets.AZURE_CONTAINER_REGISTRY }}/${{ env.AZURE_CONTAINER_REPOSITORY }}:${{ github.sha }}
kubeDeploy:
      name: kubernetesDeployment
      runs-on: ubuntu-latest
      needs: [dockerBuild]
      steps:
        - name: Checkout Manifest files
          uses: actions/checkout@v3
        - name: Set the Kubernetes context
          uses: azure/k8s-set-context@v2
          with:
            method: service-account
            k8s-url: ${{ secrets.KUBERNETES_URL }}
            k8s-secret: ${{ secrets.KUBERNETES_SECRET }} 
        - name: Deploy to the Kubernetes cluster
          uses: azure/k8s-deploy@v1
          with:
            namespace: default
            manifests: |
              sample-deployment.yaml
              test-svc.yaml
            images: |
              ${{ secrets.AZURE_CONTAINER_REGISTRY }}/${{ env.AZURE_CONTAINER_REPOSITORY }}:${{ github.sha }}
